### ISSUE TITLE
NeoVim的主题配置不生效

### ISSUE THREAD

**Issue by glepnir** [TimothyYe/mydotfiles#3]
neovim cannot find colors scheme one dark。。插件下载成功了但是好像没有在插件里面找，新建了一个colors文件夹把onedark.vim拖进去生效了。有点奇怪

**Comment by TimothyYe** [comment]
主题默认加载路径： ~/.config/nvim/colors

**Comment by glepnir** [comment]
按照vim的逻辑来看应该是这样了，话说在iterm中neovim 会有滚动条的问题，还有透明背景是如何做到的，hi Normal ctermfg=252 ctermbg=none这条命令没有生效

**Comment by TimothyYe** [comment]
滚动条？不存在的
iTerm2-> Preferences -> Appearance -> Window -> Hide Scrollbars

透明背景
iTerm2-> Preferences -> Profile -> Window -> Background Image 选一个图片，透明就是调整Blending的值

**Comment by glepnir** [comment]
deoplete这个补全只能补全函数的名字吗。不能补全函数后的括号有点坑爹， UP也是个gopher吧？是否有在studygolang社区？

**Comment by TimothyYe** [comment]
补全是那样的。
studygolang有帐号，不常去。

**Comment by glepnir** [comment]
好吧可能用IDE用惯了 冷不丁不习惯。我是社区的工作人员。有兴趣加入社区吗（PS：有点像传销了2333） 或者加群也可以。群里有一些大佬 挺热闹的

**Comment by TimothyYe** [comment]
可以，很皮

**Comment by glepnir** [comment]
很皮还行哦，貌似成都的兄弟伙，你加一群吧 一群大佬多192706294
