### ISSUE TITLE
.tmux.conf里的选项过时了，需要更新

### ISSUE THREAD

**Issue by Bittree** [TimothyYe/mydotfiles#4]
tmux source-file .tmux.conf的时候报了一堆invaild options,找了下2.9的时候报了这个issue：https://github.com/tmux/tmux/issues/1689

所以需要更新下选项，这个帖子里有人提供了python脚本来更新：https://gist.github.com/tbutts/6abf7fb5b948c066bf180922fb37adcf

跑一遍之后就可以了：）

**Comment by TimothyYe** [comment]
之前升级到2.9，一堆Tmux不兼容错误，后来我直接把本机Tmux锁定在了2.8
空了我看看

**Comment by TimothyYe** [comment]
已经更新，测试已经兼容tmux 3.1b
